//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProj.Model
{
    using GalaSoft.MvvmLight;
    using System;
    using System.Collections.Generic;
    
    public partial class Product : ObservableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }

        //private string name;
        //public string Name { get => name; set => Set(ref name, value); }

        private int? id;
        public int? Id { get => id; set => Set(ref id, value); }
        private string productName;
        public string ProductName { get => productName; set => Set(ref productName, value); }
        private int? supplierId;
        public int? SupplierId { get => supplierId; set => Set(ref supplierId, value); }
        public Nullable<decimal> UnitPrice { get; set; }
        private string package;
        public string Package { get => package; set => Set(ref package, value); }
        private bool isDiscounted;
        public bool IsDiscontinued{ get => isDiscounted; set => Set(ref isDiscounted, value); }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
